export const prefix = 'init';

export const INITIAL_FIELD_START = 'INITIAL_FIELD_START';
export const INITIAL_FIELD = `${prefix}/INITIAL_FIELD`;
export const RANDOM_LOC_SHIP_START = 'RANDOM_LOC_SHIP_START';
export const SET_MATRIX = 'SET_MATRIX';
export const ADD_SHIP = 'ADD_SHIP';
export const SET_DECK_IN_MATRIX = 'SET_DECK_IN_MATRIX';
export const ADD_SHIP_TO_SQUADRON = 'ADD_SHIP_TO_SQUADRON';

export const CLEAR_FIELD = 'CLEAR_FIELD';
export const IS_DRAGGING = 'IS_DRAGGING';
export const SET_FAKE_SHIP = 'SET_FAKE_SHIP';
export const ADD_SINGLE_SHIP_START = 'ADD_SINGLE_SHIP_START';
export const SET_DRAGGABLE_SHIP_COLLECTION = 'SET_DRAGGABLE_SHIP_COLLECTION';
