const prefix = 'enemy'

export const INITIAL_ENEMY_FIELD_START = 'INITIAL_ENEMY_FIELD_START';
export const INITIAL_ENEMY_FIELD = `${prefix}/INITIAL_ENEMY_FIELD`;
export const SET_ENEMY_MATRIX = 'SET_ENEMY_MATRIX';
export const ADD_SHIP_TO_ENEMY_SQUADRON = 'ADD_SHIP_TO_ENEMY_SQUADRON';
export const SET_DECK_IN_ENEMY_MATRIX = 'SET_DECK_IN_ENEMY_MATRIX';

export const SHOOT = 'SHOOT';
export const ADD_ELEMENT_TO_CELL = 'ADD_ELEMENT_TO_CELL';
export const UPDATE_ENEMY_CELLS = 'UPDATE_CELLS';
export const UPDATE_ENEMY_SQUADRON = 'UPDATE_ENEMY_SQUADRON';

export const SET_BLOCKED_CELL = 'SET_BLOCKED_CELL';